### PR TITLE
Geoserver e2e tests

### PR DESCRIPTION
**Pull request by ChaamC**
## Overview

Minor adjustments to the `test-geoserver-secured-access` component for the related e2e Geoserver tests

## Changes

- Adds test data and volume for `test-geoserver-secured-access`

## Related Issue / Discussion

- Related to Jira task [DAC-468](https://crim-ca.atlassian.net/browse/DAC-468) and other PR [#125](https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/125) on PAVICS-e2e-workflow-tests

### CODE REVIEW

**Comment by ChaamC** [comment]
@fmigneault 
New notebook was tested on `https://host-140-216.rdext.crim.ca/` and tests are successful.

**Comment by tlvu** [comment]
Note component `test-geoserver-secured-access` will be deprecated when https://github.com/bird-house/birdhouse-deploy/pull/348/ is merged.

**Comment by ChaamC** [comment]
> Note component `test-geoserver-secured-access` will be deprecated when #348 is merged.

@tlvu Oh, I didn't realize that. From what I see, I could move my changes to another optional-component named `test-geoserver`, which will just add my required test files as volume mounts, and I could use geoserver directly in my tests instead of the secured geoserver.

Not sure what to do here since both of the PRs' modifications are conflicting, and my current PR works with the current version of birdhouse. If I apply changes before the other PR is merged, it will probably break my e2e tests.

**Comment by ChaamC** [comment]
> Note component `test-geoserver-secured-access` will be deprecated when #348 is merged.

@tlvu Oh, I didn't realize that. From what I see, I could move my changes to another optional-component named `test-geoserver`, which will just add my required test files as volume mounts, and I could use geoserver directly in my tests instead of the secured geoserver.

Not sure what to do here since both of the PRs' modifications are conflicting, and my current PR works with the current version of birdhouse. If I apply changes before the other PR is merged, it will probably break my e2e tests.

**Review by fmigneault — APPROVED** [review]

**Comment by fmigneault** [comment]
@ChaamC @tlvu 
I think it can remain as `test-geoserver-secured-access`, just that it will only focus on adding test data for validating secured access. Not more Magpie provider defined in there.
A default set of test Magpie permissions could still be defined if needed by the test notebooks.

**Comment by fmigneault** [comment]
@ChaamC @tlvu @mishaschwartz 
IMO, if the notebook is able to run successfully and validate that secured access is possible with the current prototype setup, I would be tempted to merge this first along https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/125 when all items are addressed, and then test that the notebook still works with https://github.com/bird-house/birdhouse-deploy/pull/348. 

I think the only difference is the current `geoserver-secured` vs planned `geoserver` Magpie service, but all remaining URLs and permissions scheme should be the same. If the notebook has a `os.getenv("GEOSERVER_SECURED_SERVICE")`, we can quickly toggle over the Magpie service to test if the current working setup was properly ported in https://github.com/bird-house/birdhouse-deploy/pull/348.

**Comment by ChaamC** [comment]
@fmigneault @tlvu 
Can this PR be merged?

The other PR on `PAVICS-e2e-test-workflow` with the new notebook was merged earlier. I ran a new e2e test here and the notebook is working without fail. Just need to manually use EXTRA_TEST_ENV_VAR `GEOSERVER_SERVICE=geoserver-secured` for the tests until the changes on the `geoserver-secured`/`geoserver` services are also merged. The e2e test is made to use `geoserver` by default, so it should work when the update is done on the geoserver service.

Actually I was gonna tag PR [#348](https://github.com/bird-house/birdhouse-deploy/pull/348) which contained the changes on the geoserver service, but I see that some changes were reverted and geoserver-secured is not deprecated anymore. Do I need to update anything else on the `test-geoserver-secured-access` here ?

Also, received some errors/failures in some other e2e tests, but I don't think it is related to this PR.

**Review by tlvu — APPROVED** [review]
LGTM

**Comment by tlvu** [comment]
> @fmigneault @tlvu
> Can this PR be merged?

Yes it looks good on this end.  But please on the https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/125 side, please do not enable that notebook as part of the default test suite so it does not run by default nightly on our production instance.

**Review by fmigneault — APPROVED** [review]
LGTM. 

https://github.com/bird-house/birdhouse-deploy/pull/348 reverted changes related to deprecating `test-geoserver-secured-access` to leave it available, so that it can be used as proposed in this PR. 

The `geoserver-secured` service however will be removed in favor of `geoserver` standalone.

**Comment by fmigneault** [comment]
@tlvu 
> please on the [Ouranosinc/PAVICS-e2e-workflow-tests#125](https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/125) side, please do not enable that notebook as part of the default test suite so it does not run by default nightly on our production instance.

Shouldn't that be a config on the prod server to instead exclude this notebook from the test suite?
Notebooks added to the repo should be enabled by default.

**Comment by fmigneault** [comment]
Just saw https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/126. I'm fine with that workaround since the tests are indeed for validating auth in the case of GeoServer.  

Variable `TEST_MAGPIE_AUTH=true` is enabled for CI tests, so the feature is evaluated properly.

**Pull request merged**
