### PR TITLE
flyingpigeon: set maxsingleinputsize = 2097152000.0

### PR DESCRIPTION
**Pull request by tlvu**
Requested by @nilshempelmann for a soilmoisture data set.

This is a 2G file limit !  I wonder if it is possible to give a URL path and the WPS service will fetch the file itself so we do not have to set such a big file limit.

### CODE REVIEW

**Comment by tlvu** [comment]
@nilshempelmann new FP settings deployed to https://lvupavicsdev.ouranos.ca, can you test it works as intended before we go to prod with this.

**Comment by nilshempelmann** [comment]
@tlvu 
> @nilshempelmann new FP settings deployed to https://lvupavicsdev.ouranos.ca, can you test it works as intended before we go to prod with this.

`Invalid username or password` gues I need an valid login. can you send it per mail?

**Comment by nilshempelmann** [comment]
'ProcessSucceeded'

**Comment by tlvu** [comment]
@nilshempelmann Thanks Nils for the test, this will be auto deployed during the night by our automated system.  I can force the deployment now if you have an urgent need for it.

**Pull request merged**
