### PR TITLE
Update to new finch.

### PR DESCRIPTION
**Pull request by aulemahal**
# Overview

Updates finch's image to just released 0.7.4.

## Changes

**Non-breaking changes**
- Updates finch's xclim to 0.26.
- Finch now has improved metadata handling : output's attributes are read from config and ensemble processes's datasets are included in the attributes of the output.
- Ensemble processes now compute meaningful statistics for indicators using day-of-year "units".

### CODE REVIEW

**Comment by tlvu** [comment]
run tests

**Comment by tlvu** [comment]
@MatProv is something changed on the IAC?  I used `run tests` in the previous comment and nothing happened !

**Comment by tlvu** [comment]
@MatProv Tried to manually start an IAC, did not work as well https://daccs-jenkins.crim.ca/job/DACCS-iac/444/parameters/.  Maybe it's due to the fact that the source branch is from a fork repo and not from this repo?

**Comment by tlvu** [comment]
@MatProv I pushed aulemahal branch to this repo (https://github.com/bird-house/birdhouse-deploy/tree/update-finch) so that the source branch is not from a fork and tried to start another IAC (https://daccs-jenkins.crim.ca/job/DACCS-iac/445/parameters/), same error.

**Comment by MatProv** [comment]
> @MatProv is something changed on the IAC? I used `run tests` in the previous comment and nothing happened !

@tlvu Yes today I've disabled the hook to add a feature and avoid having random builds during this time. Will be reenabled soon. Sorry for this!

**Comment by tlvu** [comment]
@MatProv Oh fancy, even reporting the summary of the test results, I like !!!

**Comment by tlvu** [comment]
I started 2 Jenkins build on CRIM's Jenkins, so we are on the same runtime environment as the IAC:

* https://daccs-jenkins.crim.ca/job/PAVICS-e2e-workflow-tests/job/master/392/parameters/ against our prod `pavics.ouranos.ca` to baseline the state of things

* https://daccs-jenkins.crim.ca/job/PAVICS-e2e-workflow-tests/job/master/393/parameters/ against my `lvupavicsdev.ouranos.ca` that has this PR deployed.

Both all passes so I'll merge this PR by end of day if no one see any other issues.

For the failure from the IAC:

* `pavics_thredds.ipynb` must be related to the failure to create the `authtest` user that is a known Magpie bug

* `subset.ipynb` should not fail at all.  I have not had the chance to look up why, but is this a known issue?

**Comment by MatProv** [comment]
> For the failure from the IAC:
> 
> * `pavics_thredds.ipynb` must be related to the failure to create the `authtest` user that is a known Magpie bug
> * `subset.ipynb` should not fail at all.  I have not had the chance to look up why, but is this a known issue?

@tlvu I think both were related to authtest user access denied. All tests are supposed to pass as soon as the next version of magpie is released, which will contain the fix that addresses the authtest creds. @fmigneault

**Comment by fmigneault** [comment]
@MatProv  
The fix is not yet integrated. Issue https://github.com/Ouranosinc/Magpie/issues/429 
Can slide it in `3.10.2` before I add the user-registration feature. 

Will require testing #151, or even going to #143 (after further bump to 10.2). 
I leave it to @tlvu to decide if we should jump directly to 3.10.2 skipping 3.9 once built, or ignore failing tests until then.

**Review by tlvu — APPROVED** [review]

**Comment by tlvu** [comment]
> I leave it to @tlvu to decide if we should jump directly to 3.10.2 skipping 3.9 once built, or ignore failing tests until then.

I'd go to latest possible Magpie whenever it is "safe".  I'd much rather not have "known" failing tests when possible.  It's just a burden to always have to manually go inspect the test output to make sure the failures are "still known/no new errors".

**Pull request merged**
