### PR TITLE
Revert "Merge pull request #107 from bird-house/magpie-thredds"

### PR DESCRIPTION
**Pull request by tlvu**
This reverts commit 7be3eeaf0464511abc89e93d1f553de2d7413b59, reversing changes made to c0ffb413a3dff70bbe2c98c38690d6e919f11386.

PR https://github.com/bird-house/birdhouse-deploy/pull/107 upgrade path is unstable, see issue https://github.com/Ouranosinc/Magpie/issues/403 and issue https://github.com/Ouranosinc/Magpie/issues/401.

Revert so we can remove the autodeploy block on production instances and give us time to properly test any upcoming fixes.  Also unblock Finch to go to production https://github.com/bird-house/birdhouse-deploy/pull/138.

Branch https://github.com/bird-house/birdhouse-deploy/tree/restore-previous-broken-magpie-upgrade-so-we-can-work-on-a-fix created so we have a place to work on a fix.

Matching notebooks revert: https://github.com/Ouranosinc/pavics-sdi/pull/211

### CODE REVIEW

**Comment by tlvu** [comment]
@fmigneault forgot to also say we need this revert for the upcoming Finch to go in production.  The broken Magpie is basically blocking all other components to go to prod.

**Review by fmigneault — APPROVED** [review]

**Comment by tlvu** [comment]
@fmigneault For servers that accidentally already upgraded to this new broken Magpie, I assume the old Magpie will not be able to run on the Magpie DB that has already migrated.

Is there any ways to revert the migration or we juste have to delete the entire Magpie DB (`rm -rf /data/magpie_persist`) and restart fresh?

@nikola-rados @MatProv The revert has been merged, you guys can lift the autodeploy block.  A new Finch (PR https://github.com/bird-house/birdhouse-deploy/pull/138) will come out soon.

**Comment by tlvu** [comment]
@fmigneault so I did `rm -rf /data/magpie_persist` on my dev VM so I can revert to the existing Magpie 1.7.3.

In my `env.local`, `MAGPIE_ADMIN_PASSWORD` was already set to something else than the default `qwerty` but fresh Magpie 1.7.3 still come up with the default `qwerty`.  Is that expected?

@nikola-rados @MatProv If you follow my route (`rm -rf /data/magpie_persist`), remember to login to the Magpie UI and change the password of user `admin` to the matching value in `env.local`, var `MAGPIE_ADMIN_PASSWORD` because Twitcher needs that password to know what is allowed or not.

**Comment by fmigneault** [comment]
> In my `env.local`, `MAGPIE_ADMIN_PASSWORD` was already set to something else than the default `qwerty` but fresh Magpie 1.7.3 still come up with the default `qwerty`. Is that expected?

There is probably a bug in that very old version that as been corrected a long time ago. I can't say what specifically is happening for that version.

**Pull request merged**
