### PR TITLE
Remove pavics-datacatalog from stack

### LINKED ISSUE #206: :bulb: [Feature] Remove PAVICS-Datacatalog
## Description

The new intake catalogs replace the functionality of PAVICS-Datacatalog. 
I suggest we remove this component from the default deployment.

### PR DESCRIPTION
**Pull request by huard**
## Overview

The Pavics-datacatalog is not used, unmaintained, and not part of future development plans. Catalogs are currently provided by intake static files, and will eventually be accompanied by a STAC catalog. 

- Remove references to pavics-datacatalog in config and docs
- Remove solr Dockerfile
- Remove scripts triggering pavicscrawler

This PR has not been tested, and frankly, I don't know what I'm doing.

## Changes

**Non-breaking changes**
- Removes pavics-datacatalog
- Removes solr

**Breaking changes**
- Services relying on the datacatalog are not offered anymore.

## Related Issue / Discussion

- Resolves #206 

## Additional Information

Links to other issues or sources.

- [ ] Things to do...

### CODE REVIEW

**Comment by fmigneault** [comment]
Self note, need to align with https://github.com/bird-house/birdhouse-deploy/pull/284 to remove extra configs not needed anymore.

**Comment by huard** [comment]
All the notebooks seem to pass on our prod version, so not clear to me where the nb failures are coming from.

**Comment by huard** [comment]
Can this be closed ?

**Comment by fmigneault** [comment]
@huard 
For sure, the conflicts need to be resolved first, so we can get a CI "success" with the `catalog` service removed.
The CI has been succeeding for a few PRs in a row since last week (something we didn't have for a while). 
I'd like to keep it this way for following PRs.

I wonder if we should wait until STAC is included (#297), before we transition everything? 
At the very least, documentation such as https://birdhouse-deploy.readthedocs.io/en/latest/data_catalog.html# should be adjusted.
Is there any other documentation references in birdhouse/pavics/... about accessing catalogues with intake as the official approach from now on (or until STAC is there)?

**Comment by tlvu** [comment]
I think @mishaschwartz has a plan to handle all the components that will be removed or disabled.

**Comment by mishaschwartz** [comment]
@huard yes I'm working on a PR that will re-organize all the components and part of that will involve deprecating this. I was going to wait until that PR was in place to remove these ones (#287, #291, #292) but there's no reason why we can't close these first.

**Comment by huard** [comment]
Ok, I'll close the PRs. Once the big reorg is done, I can go through the docs and remove the obsolete material.

**Pull request closed without merging**
