### PR TITLE
Fix geoserver not configured properly behind proxy

### PR DESCRIPTION
**Pull request by tlvu**
Hitting https://pavics.ouranos.ca/geoserver/wfs?request=GetCapabilities&version=1.1.0

Before fix (wrong scheme and wrong port):
```
<ows:Operation name="GetCapabilities">
<ows:DCP>
<ows:HTTP>
<ows:Get xlink:href="http://pavics.ouranos.ca:80/geoserver/wfs"/>
<ows:Post xlink:href="http://pavics.ouranos.ca:80/geoserver/wfs"/>
</ows:HTTP>
</ows:DCP>
```

After fix:
```
<ows:Operation name="GetCapabilities">
<ows:DCP>
<ows:HTTP>
<ows:Get xlink:href="https://pavics.ouranos.ca:443/geoserver/wfs"/>
<ows:Post xlink:href="https://pavics.ouranos.ca:443/geoserver/wfs"/>
</ows:HTTP>
</ows:DCP>
```

This config automate manual step to set proxy base url in Geoserver UI https://docs.geoserver.org/2.9.3/user/configuration/globalsettings.html#proxy-base-url

I had to override the docker image entrypoint to edit the `server.xml` on the fly before starting Geoserver (Tomcat) since setting Java proxy config did not seem to work (see first commit).

Related to https://github.com/Ouranosinc/raven/issues/297.

Edit:
* Added "I had to override the docker image entrypoint to edit the `server.xml` on the fly before starting Geoserver (Tomcat) since setting Java proxy config did not seem to work (see first commit)."

### CODE REVIEW

**Review by huard — APPROVED** [review]
I approve the spirit of it, but cannot really comment on the actual content ; )

**Comment by tlvu** [comment]
FYI @f-PLT

**Comment by MatProv** [comment]
run tests

**Review by Zeitsperre — APPROVED** [review]
I somehow understand this! And also it looks good to me.

**Comment by f-PLT** [comment]
Great!

I'll pass this information along on our side.

**Comment by tlvu** [comment]
> Great!
> 
> I'll pass this information along on our side.

Adding @MatProv as well.

If CRIM instances have autodeploy enabled, there is nothing to do on your side, you'll just get it automatically.

**Comment by tlvu** [comment]
> I somehow understand this! And also it looks good to me.

Sorry maybe I need to explain in simple terms what I did for everyone else as well.

I had to override the docker image entrypoint to edit the `server.xml` on the fly before starting Geoserver (Tomcat) since setting Java proxy config did not seem to work (see first commit).

**Comment by MatProv** [comment]
> If CRIM instances have autodeploy enabled, there is nothing to do on your side, you'll just get it automatically.

@tlvu Yes our staging has just been updated with this change, so prod will be updated tonight, thanks to autodeploy!

**Pull request merged**
