### PR TITLE
weaver: bump version to 5.1.0 + debug notebook output

### PR DESCRIPTION
**Pull request by fmigneault**
## Overview

Debugging cause of diff in final output of https://github.com/Ouranosinc/pavics-sdi/blob/master/docs/source/notebook-components/weaver_example.ipynb

Built on top of https://github.com/bird-house/birdhouse-deploy/pull/439

## Changes

**Non-breaking changes**
- New component version Weaver: 5.1.1
- Fixes to Weaver WSP provider registration retry logic.

### CODE REVIEW

**Comment by fmigneault** [comment]
@mishaschwartz 
So, I still have no idea what could be the cause of the `hummingbird` output sporadically differing from the notebook cell, but all tests are now succeeding.

**Comment by fmigneault** [comment]
Hold up! Weaver notebook was not actually tested during that run... weird. 
🕵️ investigating

**Review by tlvu — APPROVED** [review]
LGTM.  I defer to Misha that knows more about Weaver than I do.

**Comment by fmigneault** [comment]
Found the cause. Due to invalid sourcing of `env.local` over capturing outputs to pass to `TEST_PAVICS_SDI_WEAVER`. 

PR in progress to fix (https://gitlab.com/crim.ca/clients/daccs/daccs-e2e-jenkins/-/merge_requests/33). Will rerun once integrated.

**Pull request merged**
