### PR TITLE
Magpie/Twitcher 3.15.1 + debug logging & gunicorn 

### PR DESCRIPTION
**Pull request by fmigneault**
## Overview

Attempt to fix issues related to intermittent errors related to caching feature.

## Changes

**Non-breaking changes**
  - Magpie/Twitcher: update to version 3.15.1

    * Apply additional DEBUG logging entries to attempt resolving issues related to caching.
      See also [Ouranosinc/Magpie#466](https://github.com/Ouranosinc/Magpie/issues/466).
    * Adjust Twitcher runner to employ `gunicorn` instead of `waitress`.

**Breaking changes**
- n/a

## Related Issue / Discussion

- relates to (fixes?) https://github.com/Ouranosinc/Magpie/issues/466

### CODE REVIEW

**Comment by tlvu** [comment]
LGTM, thanks!  Will deploy this to our Staging now, see if we still can reproduce the weirdo error or not.  For deployment to prod, I think we should revert to INFO logging.

**Comment by tlvu** [comment]
This PR deployed on our https://medus.ouranos.ca right now.  Feel free to hit it from CRIM Jenkins as well.

**Comment by fmigneault** [comment]
>  For deployment to prod, I think we should revert to INFO logging.

Yes definitively. This PR is for testing only. Revert to INFO if it works.

**Comment by fmigneault** [comment]
run tests

**Comment by fmigneault** [comment]
run tests

**Comment by matprov** [comment]
@fmigneault Our disk quota has been reached again on the infra. I've asked to grow it a bit, since we only have 8 daccs instances up and quota is reached.

**Comment by fmigneault** [comment]
@matprov 

> Our disk quota has been reached again on the infra.

I noticed that. I removed 2 instances that were >2 weeks old.

**Comment by matprov** [comment]
> @fmigneault Our disk quota has been reached again on the infra. I've asked to grow it a bit, since we only have 8 daccs instances up and quota is reached.

Done. From 1.6tb to 3tb for the quota. We should be good for a while with this limit.

**Comment by tlvu** [comment]
> [2021-11-24T19:24:09.024Z] finch-master/docs/source/notebooks/finch-usage.ipynb .F..F.              [ 65%]

Merge with latest, there is a new Finch that fixed this error.

**Comment by fmigneault** [comment]
@tlvu  I'm only interested in `stress-tests.ipynb` here. This PR won't be merged as it would be superseded by #224

**Comment by fmigneault** [comment]
run tests

**Comment by fmigneault** [comment]
run tests

**Comment by fmigneault** [comment]
@ChaamC 
Good to go with your PR based on https://github.com/bird-house/birdhouse-deploy/pull/197#issuecomment-984957460 🚀

**Pull request closed without merging**
