### PR TITLE
Autodeploy: optionally fix file permissions

### PR DESCRIPTION
**Pull request by mishaschwartz**
## Overview

The autodeploy mechanism creates new files owned by root. If this is not desired then users have to manually update the file ownership after each autodeployment. This adds an option to change the ownership of all files to a specific user after each autodeployment. 

For example, if the code in this repo is currently owned by a user named `birduser` with uid 1002, then by setting `export AUTODEPLOY_CODE_OWNERSHIP="1002:1002"` in `env.local`, all files and folders in this repo will continue to be owned by `birduser` after each autodeployment. 

## Changes

**Non-breaking changes**

adds an optional environment variable to env.local

**Breaking changes**

None

### CODE REVIEW

**Review by tlvu — APPROVED** [review]
LGTM thanks !

**Comment by tlvu** [comment]
Humm, funny this permission problem is the root cause since `birdhouse/deployment/fix-write-perm` was meant to specifically fix this kind of permission problem.  Or maybe I did not fully understand the usage of `setfacl`.  Thanks for catching this.

**Comment by tlvu** [comment]
I think this fixes https://github.com/bird-house/birdhouse-deploy/issues/342

**Review by fmigneault — APPROVED** [review]

**Comment by mishaschwartz** [comment]
> I think this fixes https://github.com/bird-house/birdhouse-deploy/issues/342

I just double checked and unfortunately it does not fix that issue

**Pull request merged**
