### PR TITLE
Add terms conditions to JupyterHub login page and update to latest JupyterHub version

### PR DESCRIPTION
**Pull request by tlvu**
User have to check the checkbox agreeing to the terms and conditions in order to login (fixes https://github.com/Ouranosinc/pavics-sdi/issues/188).

User will have to accept the terms and conditions (the checkbox) each time he needs to login. However, if user do not logout or wipe his browser cookies, the next time he navigate to the login page, he'll just log right in, no password is asked so no terms and conditions to accept either.

This behavior is optional and only enabled if `JUPYTER_LOGIN_TERMS_URL` in `env.local` is set.

Had to patch the `login.html` template from jupyterhub docker image for this feature (PR https://github.com/jupyterhub/jupyterhub/pull/3264).

Also update jupyterhub docker image to latest version.

Deployed to my test server https://lvupavics.ouranos.ca/jupyter/hub/login (pointing to a bogus terms and conditions link for now).

Tested on Firefox and Google Chrome.

Tested that upgrade from jupyterhub `1.0.0` to `1.2.1` is completely transparent to already logged in jupyter users.
```
[D 2020-11-18 19:53:52.517 JupyterHub app:2055] Verifying that lvu is running at http://172.18.0.3:8888/jupyter/user/lvu/                             
[D 2020-11-18 19:53:52.523 JupyterHub utils:220] Server at http://172.18.0.3:8888/jupyter/user/lvu/ responded with 302                                
[D 2020-11-18 19:53:52.523 JupyterHub _version:76] jupyterhub and jupyterhub-singleuser both on version 1.2.1                                         
[I 2020-11-18 19:53:52.524 JupyterHub app:2069] lvu still running    
```

recorded

Edit:

* Add corresponding jupyterhub PR https://github.com/jupyterhub/jupyterhub/pull/3264
* Add "Tested on Firefox and Google Chrome."
* Add "User will have to accept the terms and conditions (the checkbox) each time he needs to login. However, if user do not logout or wipe his browser cookies, the next time he navigate to the login page, he'll just log right in, no password is asked so no terms and conditions to accept either."
* Add "Tested that upgrade from jupyterhub 1.0.0 to 1.2.1 is completely transparent to already logged in jupyter users."

### CODE REVIEW

**Review by huard — APPROVED** [review]
Is this a one-time thing ? Or users will need to accept every time they login ?

**Comment by tlvu** [comment]
> Is this a one-time thing ? Or users will need to accept every time they login ?

We do not keep which user accepted so every time they login.

However, if they do not signout or do not clear their cookies, next time they arrive to the page, they won't need to login.

**Review by MatProv — APPROVED** [review]

**Review by tlogan2000 — APPROVED** [review]

**Review by dbyrns — APPROVED** [review]
We will be able soon to add terms and conditions that must be accepted for joining groups too. Do you think it might be a good idea to prepare a directory of "terms and conditions" hosted by nginx to serve them? Or do you plan to host it elsewhere?

**Comment by tlvu** [comment]
> We will be able soon to add terms and conditions that must be accepted for joining groups too. 

Joining what group?  Magpie group?

> Do you think it might be a good idea to prepare a directory of "terms and conditions" hosted by nginx to serve them? Or do you plan to host it elsewhere?

So far we are just thinking a direct link to some `.md` file somewhere on github.  So user can easily diff the changes as the terms and conditions evolve.

The go-live will have this option disabled since the `.md` file is not ready yet.

**Comment by tlvu** [comment]
@tlogan2000 @huard I got feedback from the corresponding PR I submitted on jupyterhub side (https://github.com/jupyterhub/jupyterhub/pull/3264#discussion_r527514546)

They suggested an alternate way to implement this.  Basically instead of toggling disabling/enabling the submit button using javascript, we make the checkbox "required" so submit button is not disabled but will do nothing and recall user to check the checkbox.

recorded

I think it's better because:
* no javascript required at all
* user get a pop-up notifying them they need the checkbox

You guys okay with this change?

**Comment by tlogan2000** [comment]
Ok for me.

**Comment by dbyrns** [comment]
Ok too.

**Pull request merged**
