### PR TITLE
Script to batch create magpie users

### PR DESCRIPTION
**Pull request by tlvu**
Script to batch create 25 magpie users for issue https://github.com/Ouranosinc/raven/issues/251.  Also useful to delete those test users after it's done.

Found https://github.com/Ouranosinc/Magpie/issues/355 and https://github.com/Ouranosinc/Magpie/issues/354 while writing that script.

@huard @tlogan2000 Just for your info.

### CODE REVIEW

**Review by fmigneault — APPROVED** [review]
looks good
only needs update of tag when issue https://github.com/Ouranosinc/Magpie/issues/355 is patched

**Review by moulab88 — APPROVED** [review]

**Comment by tlvu** [comment]
> only needs update of tag when issue [Ouranosinc/Magpie#355](https://github.com/Ouranosinc/Magpie/issues/355) is patched

@fmigneault thinking of fixing it soon and cut a release?  Else I can just merge this PR now and open a new PR to pull in new Magpie docker later.  No rush.

**Comment by fmigneault** [comment]
> 
> 
> > only needs update of tag when issue [Ouranosinc/Magpie#355](https://github.com/Ouranosinc/Magpie/issues/355) is patched
> 
> @fmigneault thinking of fixing it soon and cut a release? Else I can just merge this PR now and open a new PR to pull in new Magpie docker later. No rush.

see https://github.com/Ouranosinc/Magpie/pull/358

**Comment by fmigneault** [comment]
@tlvu I pushed a `2.0.1` tag. The docker should be ready in a few minutes.

**Pull request merged**
