### PR TITLE
Update .zenodo.json

### LINKED ISSUE #299: :bulb: [Feature] Issue DOI
## Description

Improve discoverability of software.

- [ ] Connect to Zenodo to get a DOI
- [ ] Make a release to mint DOI

### PR DESCRIPTION
**Pull request by huard**
## Overview

Update zenodo config

## Changes

**Non-breaking changes**
- Add Misha to creators
- Add birdhouse community

## Related Issue / Discussion

- Resolves #299

### CODE REVIEW

**Review by Zeitsperre — APPROVED** [review]
LGTM. Do we want to add full affiliation names ?

**Comment by tlvu** [comment]
Does this need to be merged before resubmitting the Raven paper?

**Comment by huard** [comment]
Ideally, but not a blocker.

**Comment by tlvu** [comment]
Created a release https://github.com/bird-house/birdhouse-deploy/releases/tag/1.26.2, hopefully Zenodo picked it up.

**Pull request merged**
