### PR TITLE
update `Magpie==4.1.1` and `Twitcher==0.10.0`

### PR DESCRIPTION
**Pull request by fmigneault**
## Overview
Security updates.

## Changes

**Non-breaking changes**
- Magpie/Twitcher: update Python packages and base Docker image to address security vulnerabilities 

  - [Magpie 4.1.1](https://github.com/Ouranosinc/Magpie/blob/master/CHANGES.rst#411-2024-07-23)     (relates to [Ouranosinc/Magpie#622](https://github.com/Ouranosinc/Magpie/pull/622)).
  - [Twitcher 0.10.0](https://github.com/bird-house/twitcher/blob/master/CHANGES.rst#0100-2024-07-22)     (relates to [bird-house/twitcher#136](https://github.com/bird-house/twitcher/pull/136)).

**Breaking changes**
- n/a

## Related Issue / Discussion

PRs that are an agglomeration of vulnerability fixes flagged by Snyk.

- https://github.com/Ouranosinc/Magpie/pull/622
- https://github.com/bird-house/twitcher/pull/136

## Additional Information

- The change from Magpie 3.x to 4.x is caused by the drop of Python 3.5 to 3.7, and the addition of 3.12 some time ago. Major version was used only to highlight this change in case older versions were still employed by some instances. From a technical aspect in birdhouse-deploy, Magpie with Python 3.11 was already in use for a while (see https://github.com/Ouranosinc/Magpie/blob/3.38.0/Dockerfile#L1). Only minor package dependency differences are actually expected.

## CI Operations

birdhouse_daccs_configs_branch: master
birdhouse_skip_ci: false

### CODE REVIEW

**Review by tlvu — APPROVED** [review]
Looks good to me but I see the IaC pipeline did not trigger again !!!  Could this PR at least pass under the IaC pipeline because I don't be performing manual verification this time.

I have the impression the IaC pipeline has not triggered automatically since a few weeks already.  I already noticed this with the GeoServer upgrade.

**Comment by fmigneault** [comment]
Manual trigger: http://daccs-jenkins.crim.ca/job/DACCS-iac-birdhouse/2742/

**Comment by tlvu** [comment]
FYI le notebook cowbird n'a pas passé.

**Comment by fmigneault** [comment]
@tlvu
Thanks. Will need to investigate some more... 
The error seems to be caused by a JSON parsing issue on the Jupyter API endpoint.
Not sure what could have caused it since all other notebooks doing Magpie logins worked... 
Maybe I will have time Friday, but might be delayed until the end of August otherwise.

**Comment by fmigneault** [comment]
run tests

**Comment by fmigneault** [comment]
run tests

**Comment by fmigneault** [comment]
@tlvu 
Requesting review again since it's been a while. I want to make sure it doesn't cause a surprise on your side.
The triggers are working again though! 🎉 
Seems like the Cowbird test are working now, might have been just a sporadic issue? 

Looks like the WMS is still failing. This once is very sporadic. 
Each of the failing tests below are caused by this WMS notebook, but we can see it also passes ~½ times.
{AF96DEFE-03E6-4E91-90A9-DD933A55C87F}

**Comment by tlvu** [comment]
> Requesting review again since it's been a while. I want to make sure it doesn't cause a surprise on your side.

Is there any DB upgrade?  Otherwise it should be fine.

**Review by tlvu — APPROVED** [review]
LGTM

**Pull request merged**
