### PR TITLE
weaver: bump version to 5.6.0

### PR DESCRIPTION
**Pull request by fmigneault**
## Overview

See changes in https://pavics-weaver.readthedocs.io/en/latest/changes.html#changes-5-6-1
Running here: https://hirondelle.crim.ca/weaver/versions
Corresponding changes evaluated during OGC initiatives with cross-platform provider interoperability tests.

## Changes

**Non-breaking changes**

- Weaver: bump version to [5.6.1](https://github.com/crim-ca/weaver/tree/5.6.1).

  - See full changes details in [Weaver changes](https://pavics-weaver.readthedocs.io/en/latest/changes.html#changes-5-6-1)
  - In summary:
    - multiple control setting options to customize some behaviors
    - improved *OGC API - Processes* standard conformance
    - improved support of *Common Workflow Language (CWL)* features (secrets, sub-workflow, auth-propagation, etc.)

- Weaver: WPS retry logic on post-compose step.
  - Apply `--network birdhouse_default` to the Docker `curl` image to allow HTTP requests to properly resolve
    against the running services (WPS bird providers, Weave and Magpie). In some cases, this network would not
    be automatically resolved.
  - Fix the index used during HTTP request retry to avoid going one step over the intended retry attempts.

**Breaking changes**
- n/a

## Related Issue / Discussion

- Closes https://github.com/bird-house/birdhouse-deploy/pull/439
  Merge the PR since it has issues running the CI somehow. Replace by this one all together. 

## CI Operations

birdhouse_daccs_configs_branch: master
birdhouse_skip_ci: false

### CODE REVIEW

**Review by mishaschwartz — APPROVED** [review]
I mean it all looks good to me but that same test cell is failing with the same problem. I don't really know what the cause could be for that.

**Comment by fmigneault** [comment]
@huard 
Do you know if anything changed in the reference file that could cause `hummingbird` to fail the `ncdump`?

Running it on `hirondelle`, which still use the older `birdhouse-deploy=1.42.2` tag, and `hummingbird=0.5_dev`, I get the same output file with contents `Error: generating ncdump failed. Output:`. I'm starting to think the cause could be from the input file itself.

https://hirondelle.crim.ca/twitcher/ows/proxy/hummingbird?service=WPS&request=Execute&identifier=ncdump&version=1.0.0&dataInputs=dataset_opendap=/twitcher/ows/proxy/thredds/dodsC/birdhouse/testdata/ta_Amon_MRI-CGCM3_decadal1980_r1i1p1_199101-200012.nc

**Comment by tlvu** [comment]
@fmigneault we do have a `notebooks/hummingbird.ipynb` so maybe you could use the same input file as that notebook in your weaver notebook?  That hummingbird notebook runs nightly so we are sure the test input file and the hummingbird service both work.

**Comment by fmigneault** [comment]
@tlvu 
I don't think the issue is on the Weaver side, since it only collects the text file from hummingbird, and if the hummingbird process failed completely, it would not reach the point of reading the file.

I can run the WPS request on hummingbird on this CI test server: 
https://host-140-118.rdext.crim.ca/twitcher/ows/proxy/hummingbird?service=WPS&request=Execute&identifier=ncdump&version=1.0.0&dataInputs=dataset_opendap=https://host-140-118.rdext.crim.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/testdata/ta_Amon_MRI-CGCM3_decadal1980_r1i1p1_199101-200012.nc
generating:
https://host-140-118.rdext.crim.ca/wpsoutputs/hummingbird/1db03ea2-29d2-11ef-9a15-0242ac1e0211/nc_dump_mII_kU.txt

I can also look at the resulting file when the execution is performed by the notebook with Weaver: 
https://host-140-118.rdext.crim.ca/wpsoutputs/weaver/public/9f597496-358a-4c16-87e0-b4567d880254/output/nc_dump_MZ84Fh.txt

I am really confused about the cause of that error...

**Comment by fmigneault** [comment]
*Update:* found the potential cause.

Somewhere along the Weaver->CWL->WPS chain, either OWSLib or PyWPS inject an empty file for the `dataset` input, on top of the provided `dataset_opendap` URL. This causes `hummingbird` `ncdump` to actually receive 2 "inputs", one being an invalid NetCDF and the expected OpenDAP reference. This explains why both the error message and the expected NetCDF text dump are displayed simultaneously. 

Digging deeper for a fix to avoid this empty input injection...

**Comment by fmigneault** [comment]
OK, so Weaver's tests are working again now, but I'm getting new errors from GeoServer tests and the stress-test. 

@mishaschwartz @tlvu Any chance those errors are introduced by https://github.com/bird-house/birdhouse-deploy/pull/463/commits/f252ee8ad5af827a1163f85ed9fa30ffb76a0bee including latest birdhouse-deploy changes as well? 
Both GeoServer and THREDDS (used in stress test) are somewhat irrelevant for Weaver.

**Comment by fmigneault** [comment]
Running build: http://daccs-jenkins.crim.ca/job/DACCS-iac-birdhouse/ to test if master can run on its own without this PR's change.

**Comment by mishaschwartz** [comment]
> Any chance those errors are introduced by https://github.com/bird-house/birdhouse-deploy/commit/f252ee8ad5af827a1163f85ed9fa30ffb76a0bee

I can see that the Jenkins tests didn't run for https://github.com/bird-house/birdhouse-deploy/pull/462 so it's possible. Do we know why some PRs don't trigger the Jenkins tests so we can avoid this in the future?

**Comment by tlvu** [comment]
> OK, so Weaver's tests are working again now, but I'm getting new errors from GeoServer tests and the stress-test.
> 
> @mishaschwartz @tlvu Any chance those errors are introduced by [f252ee8](https://github.com/bird-house/birdhouse-deploy/commit/f252ee8ad5af827a1163f85ed9fa30ffb76a0bee) including latest birdhouse-deploy changes as well? Both GeoServer and THREDDS (used in stress test) are somewhat irrelevant for Weaver.

@fmigneault pretty sure 100% not related to that autodeploy change since CRIM Jenkins do not autodeploy anything.

That said, for stress-test I also see random errors on our side, on our staging machines where we track `master`.  Much less frequent on our production system were we track our own fork with the caching in Magpie/Twitcher disabled.

**Review by tlvu — APPROVED** [review]
Approve in spirit as I do not use Weaver.

**Comment by fmigneault** [comment]
run tests

**Comment by fmigneault** [comment]
@mishaschwartz @tlvu ⬆️ Retested and everything worked. Seems like the previous errors were sporadic issues...

**Pull request merged**
