### PR TITLE
add weaver component diagram

### PR DESCRIPTION
**Pull request by fmigneault**
## Overview

Provide contextual details about weaver and other services to help platform maintainers understand their implications.

## Changes

**Non-breaking changes**
- documentation:
  - Add `Weaver` component diagram to better illustrate its interactions with other *birdhouse* services.
  - Move `monitoring` component images under its respective component directory.

**Breaking changes**
*n/a*

## Related Issue / Discussion
*n/a*

### CODE REVIEW

**Review by tlvu — APPROVED** [review]
Super!  Thanks.

I assume the source file to generate the Weaver component diagram is in the Weaver repo?

**Comment by fmigneault** [comment]
> Super! Thanks.
> 
> I assume the source file to generate the Weaver component diagram is in the Weaver repo?

It's not in the repo because it refers to components that are not necessarily part of Weaver itself. 
I can share it with you though if you need it at some point.

**Comment by fmigneault** [comment]
FYI 
I merged in master without a new bump tag, since there is nothing really new for the stack definition.

**Comment by tlvu** [comment]
> FYI I merged in master without a new bump tag, since there is nothing really new for the stack definition.

Yeah that's perfect.  Tags not required if no code change.

**Pull request merged**
