### PR TITLE
bump weaver to 4.22.0 by default - fixes for WPS remote provider execution

### PR DESCRIPTION
**Pull request by fmigneault**
## Overview

While working on https://github.com/crim-ca/weaver/pull/455, I found some errors parsing I/O during remote WPS processes execution. 

When the stack is evaluated with `weaver` component enabled, we can see that the test process `ncdump` on WPS `hummingbird` fails (process description works, but its execution fails at some point). For example, see failures in `pavics-sdi-master/docs/source/notebook-components/weaver_example.ipynb` output in https://github.com/bird-house/birdhouse-deploy/pull/253#issuecomment-1208753167.

<details>
<summary>Test Failure Details</summary>
<pre>
<code>
20:03:05  ---------------------------------------------------------------------------
20:03:05  AssertionError                            Traceback (most recent call last)
20:03:05  Input In [10], in <cell line: 8>()
20:03:05        6 path = f"{status_location}/results"
20:03:05        7 resp = requests.get(path, **WEAVER_TEST_REQUEST_XARGS)
20:03:05  ----> 8 assert resp.status_code == 200, f"Failed to retrieve job results location [{path}]. Code: [{resp.status_code}]."
20:03:05        9 body = resp.json()
20:03:05       11 # Here, our target output ID is named 'output' according to the process description
20:03:05  
20:03:05  AssertionError: Failed to retrieve job results location [https://host-140-44.rdext.crim.ca/weaver/providers/hummingbird/processes/ncdump/jobs/a66022f6-3897-4304-9b73-aa1e5de5423b/results]. Code: [400].
20:03:05  
20:03:05  =========================== short test summary info ============================
20:03:05  FAILED pavics-sdi-master/docs/source/notebooks/esgf-dap.ipynb::Cell 0
20:03:05  FAILED pavics-sdi-master/docs/source/notebook-components/weaver_example.ipynb::Cell 3
20:03:05  FAILED pavics-sdi-master/docs/source/notebook-components/weaver_example.ipynb::Cell 8
20:03:05  FAILED pavics-sdi-master/docs/source/notebook-components/weaver_example.ipynb::Cell 9
20:03:05  ============ 4 failed, 239 passed, 3 skipped in 1032.11s (0:17:12) =============
<br>
<br>
[2022-08-08T23:56:06.182Z] pavics-sdi-master/docs/source/notebook-components/weaver_example.ipynb . [ 57%]
[2022-08-08T23:56:16.309Z] ..F....FF.                                                               [ 61%]
</code>
</pre>
</details>

If the cause was the same as the one detected in the Weaver PR, tests should start passing. 

## Changes

**Non-breaking changes**
  * Minor improvements to facilitate retrieval of XML and JSON Process definition and their seamless execution with 
    XML or JSON request contents using either WPS or *OGC API - Processes* REST endpoints interchangeably.
  * Fixes to WPS remote provider parsing registered in Weaver to successfully perform the relevant process executions.

**Breaking changes**
- n/a

## Related Issue / Discussion

- https://github.com/crim-ca/weaver/pull/455

### CODE REVIEW

**Comment by fmigneault** [comment]
run tests

**Comment by fmigneault** [comment]
Somewhat weird result from https://github.com/bird-house/birdhouse-deploy/pull/255#issuecomment-1215767202 
Both a failed and successful execution can be found in the logs... will need more investigation to figure out what happened. 
[weaver-wps-hummingbird-ncdump-job-failure-and-success.log](https://github.com/bird-house/birdhouse-deploy/files/9339936/weaver-wps-hummingbird-ncdump-job-failure-and-success.log)

The fix seems to (sometime) work though, since one execution completed successfully. 
Looking at the failing case, the error seem deep within `owslib`. Probably failing WPS (hummingbird uses an old `pywps=4.0.0`, where I have seen weird db sync issues happen before on local debug instance).

**Review by tlvu — APPROVED** [review]
LGTM

**Review by francisPLT — APPROVED** [review]

**Review by matprov — APPROVED** [review]

**Comment by fmigneault** [comment]
run tests

**Comment by fmigneault** [comment]
run tests

**Comment by fmigneault** [comment]
run tests

**Pull request merged**
