### PR TITLE
Update to raven 0.13.0

### PR DESCRIPTION
**Pull request by cjauvin**
This updates raven to 0.13.0, which corresponds to the work done in these PRs:

* https://github.com/Ouranosinc/raven/pull/384
* https://github.com/Ouranosinc/raven/pull/385
* https://github.com/Ouranosinc/raven/pull/386

This was needed following the upgrade to RavenPy 0.5

### CODE REVIEW

**Comment by tlvu** [comment]
run tests

**Comment by MatProv** [comment]
Hi @cjauvin, fyi the failed test related to `pavics_thredds.ipynb` is unrelated to this PR.
For tests related to raven, i'm not aware if they were passing on the master branch, since these raven tests were previously disabled on the e2e test.
I've relaunched the tests after enabling the raven tests, so you might consider looking at the PAVICS-e2e-workflow-tests results for in-depth explanations on failures.

**Comment by tlvu** [comment]
@MatProv no worries, I am working with Christian, introducing him to our testing infra and all its "exceptions".  I'll work with Christian.

> For tests related to raven, i'm not aware if they were passing on the master branch, since these raven tests were previously disabled on the e2e test.

All Raven notebooks works, except 1 due to missing testdata on Thredds (existing issue https://github.com/Ouranosinc/raven/issues/383).  Raven notebooks also need `--nbval-lax`.  So for the moment Raven tests can not be enabled by default.

**Comment by tlvu** [comment]
Manual Jenkins build for Raven: https://daccs-jenkins.crim.ca/job/PAVICS-e2e-workflow-tests/job/master/443/console

All passed except 2 notebooks:
* Assess_probabilistic_flood_risk.ipynb: I think due to missing `thredds/fileServer/birdhouse/testdata/raven/raven-gr4j-cemaneige/Salmon-River-Near-Prince-George_meteo_daily.nc` testdata.  @cjauvin maybe switch this one to the dymamic way to get Raven testdata, like the rest of the notebooks?
* Full_process_example_1.ipynb: known error, existing issue https://github.com/Ouranosinc/raven/issues/383

```
5:24:59  raven-master/docs/source/notebooks/Assess_probabilistic_flood_risk.ipynb . [  7%]
15:25:01  FF.FFF                                                                   [ 11%]
15:25:14  raven-master/docs/source/notebooks/Climatological_ESP_forecasting.ipynb . [ 12%]
15:25:46  ......                                                                   [ 15%]
15:26:04  raven-master/docs/source/notebooks/Comparing_hindcasts_and_ESP_forecasts.ipynb . [ 16%]
15:26:12  .......                                                                  [ 20%]
15:26:18  raven-master/docs/source/notebooks/Extract_geographical_watershed_properties.ipynb . [ 21%]
15:26:35  ................                                                         [ 31%]
15:26:55  raven-master/docs/source/notebooks/Full_process_example_1.ipynb ........ [ 35%]
15:27:01  ...F.FFF                                                                 [ 40%]
15:27:12  raven-master/docs/source/notebooks/Hydrological_hindcasting.ipynb ...... [ 44%]
15:27:13  .                                                                        [ 45%]
15:27:21  raven-master/docs/source/notebooks/Hydrological_realtime_forecasting.ipynb . [ 45%]
15:28:18  ...                                                                      [ 47%]
15:28:31  raven-master/docs/source/notebooks/Model_calibration.ipynb ......        [ 51%]
15:28:40  raven-master/docs/source/notebooks/Multimodel_simulations.ipynb ......   [ 54%]
15:28:47  raven-master/docs/source/notebooks/Multiple_watersheds_simulation.ipynb . [ 55%]
15:28:52  .....                                                                    [ 58%]
15:28:58  raven-master/docs/source/notebooks/Parameter_ensemble_simulations.ipynb . [ 59%]
15:29:00  ....                                                                     [ 61%]
15:29:12  raven-master/docs/source/notebooks/Perform_Regionalization.ipynb ....... [ 65%]
15:29:12  ...                                                                      [ 67%]
15:29:29  raven-master/docs/source/notebooks/Region_selection.ipynb .........      [ 73%]
15:29:35  raven-master/docs/source/notebooks/Running_HMETS_with_CANOPEX_dataset.ipynb . [ 73%]
15:30:18  ..............                                                           [ 82%]
15:30:25  raven-master/docs/source/notebooks/Running_hydrological_models_on_a_remote_server.ipynb . [ 82%]
15:30:29  .......                                                                  [ 87%]
15:30:34  raven-master/docs/source/notebooks/Subset_climate_data_over_watershed.ipynb . [ 87%]
15:30:53  ......                                                                   [ 91%]
15:31:21  raven-master/docs/source/notebooks/time_series_analysis.ipynb .......... [ 97%]
15:31:34  ....                                                                     [100%]
```

**Review by tlvu — APPROVED** [review]
I am okay to merge this PR as-is.  The case of missing testdata for 2 notebooks can be addressed in a different PR since Raven notebooks are not enabled by default currently.

Please copy/paste the PR description into the merge description to keep a trace in the git repo as well.

**Pull request merged**
