### PR TITLE
Deprecate `stac-populator` optional component

### PR DESCRIPTION
**Pull request by mishaschwartz**
## Overview

This component has not been functional since it was deprecated in https://github.com/crim-ca/stac-populator/pull/12

## Changes

**Non-breaking changes**
- deprecates non-functional component

**Breaking changes**
None

## Additional Information

Links to other issues or sources.

## CI Operations

birdhouse_daccs_configs_branch: master
birdhouse_skip_ci: false

### CODE REVIEW

**Review by fmigneault — CHANGES_REQUESTED** [review]
Not sure what you mean by it not working.
It runs each time I reboot the STAC components. 

```shell
pavics-compose logs -f --tail 100 stac-populator 

[...]
stac-populator     | [INFO] STAC item [65e1ae2daea7231392c89b320c854562] already exists on [http://stac:8000/stac/collections/c604ffb6d610adbb9a6b4787db7b8fd7] (409), updating..
stac-populator     | {
stac-populator     |     "id": "614d9747c2a022a5200565e6904a2ff6",
stac-populator     |     "body": {
stac-populator     |         "type": "asset",
stac-populator     |         "properties": {
stac-populator     |             "uri": "https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/disk2/cccs_portal/indices/Final/BCCAQv2_CMIP6/txgt_29/MS/ssp585/simulations/txgt_29_mon_BCCAQ2v2+ANUSPLIN300_FGOALS-g3_historical+ssp585_1950-2100.nc",
stac-populator     |             "filename": "txgt_29_mon_BCCAQ2v2+ANUSPLIN300_FGOALS-g3_historical+ssp585_1950-2100.nc",
stac-populator     |             "extension": ".nc",
stac-populator     |             "dataset_name": "BCCAQv2_CMIP6",
stac-populator     |             "variable_id": "txgt_29",
stac-populator     |             "freq": "MS",
stac-populator     |             "scenario": "ssp585",
stac-populator     |             "collection_id": "CMIP6"
stac-populator     |         },
stac-populator     |         "categories": [
stac-populator     |             "data"
stac-populator     |         ],
stac-populator     |         "item_id": "eda9db16602332a26d6bf6df77387a46"
stac-populator     |     }
stac-populator     | }
stac-populator     | [INFO] STAC item [eda9db16602332a26d6bf6df77387a46] already exists on [http://stac:8000/stac/collections/c604ffb6d610adbb9a6b4787db7b8fd7] (409), updating..
stac-populator     | 2024-11-27 03:35:02,924 stac_generator.plugins.extraction_methods.regex INFO Found matches for regex extract
stac-populator     | 2024-11-27 03:35:02,925 stac_generator.plugins.extraction_methods.header.header WARNING Header extract backend not found for https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/disk2/cccs_portal/indices/Final/BCCAQv2/txgt_32/YS/rcp45/simulations_spatialAvgCensus/BCCAQv2+ANUSPLIN300_MPI-ESM-MR_historical+rcp45_r1i1p1_1950-2100_txgt_32_YS_spatialAvgCensus.nc
stac-populator     | 2024-11-27 03:35:02,948 stac_generator.plugins.extraction_methods.object_store_stats INFO Extracting metadata for: https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/disk2/cccs_portal/indices/Final/BCCAQv2_CMIP6/txgt_29/MS/ssp585/simulations/txgt_29_mon_BCCAQ2v2+ANUSPLIN300_EC-Earth3-Veg_historical+ssp585_1950-2100.nc with checksum: None
stac-populator     | 2024-11-27 03:35:02,980 stac_generator.plugins.extraction_methods.object_store_stats INFO Extracting metadata for: https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/disk2/cccs_portal/indices/Final/BCCAQv2/txgt_32/YS/rcp45/simulations_spatialAvgCensus/BCCAQv2+ANUSPLIN300_MPI-ESM-LR_historical+rcp45_r1i1p1_1950-2100_txgt_32_YS_spatialAvgCensus.nc with checksum: None
stac-populator     | [INFO] STAC collection [c604ffb6d610adbb9a6b4787db7b8fd7] already exists on [http://stac:8000/stac] (409), updating..
stac-populator     | [INFO] STAC collection [0798aa197d54eb4332767a5a4077fb0f] already exists on [http://stac:8000/stac] (409), updating..
stac-populator     | STAC asset generator ran for 200 seconds. Exiting.
stac-populator exited with code 0
```

Collections are properly validated/updated against existing/added files: 
https://hirondelle.crim.ca/stac/collections/c604ffb6d610adbb9a6b4787db7b8fd7

I agree it needs some updates to make it work with latest changes in the repo (CLI refactor and all), but the component is not broken in its current state with the way it's defined.

**Comment by mishaschwartz** [comment]
You're using an old version of the image that is cached locally on your machine.

The image is tagged with `:master` which means that it is not properly versioned and it is updated as the codebase changes.

```sh
docker image rm ghcr.io/crim-ca/stac-populator:master
docker run ghcr.io/crim-ca/stac-populator:master ./populate.sh  # this exits with the message "./populate.sh: no such file or directory"
```

**Comment by fmigneault** [comment]
Tag `:master` is not an auto-updated tag. It is just a poorly named 1-year old tag.
It is not cached locally. It is the same one that is regularly retrieved from: 
https://github.com/crim-ca/stac-populator/pkgs/container/stac-populator/148542132?tag=master

**Comment by mishaschwartz** [comment]
What happens when you try this?

> docker image rm ghcr.io/crim-ca/stac-populator:master
> docker run ghcr.io/crim-ca/stac-populator:master ./populate.sh  # this exits with the message "./populate.sh: no such file or directory"

**Comment by fmigneault** [comment]
Here it is: https://github.com/crim-ca/stac-populator/pkgs/container/stac-populator/98905655?tag=0.0.0
IT matches an existing sha256 that was already in the container registry.

**Pull request closed without merging**
