### PR TITLE
upgrade Finch to 0.8.0

### PR DESCRIPTION
**Pull request by huard**
## Overview

Please include a summary of the changes and which issues are fixed. 

Please also include relevant motivation and context. 

List any dependencies that are required for this change.

## Changes

**Non-breaking changes**

- Updated changelog by @matprov 
- Add hourly_to_daily process by @huard 
- Avoid annoying warnings by updating birdy (environment-docs) by @huard 
- Upgrade to clisops 0.8.0 to accelerate spatial averages over regions.
- Upgrade to xesmf 0.6.2 to fix spatial averaging bug not weighing correctly cells with varing areas.
- Update to PyWPS 4.5.1 to allow the creation of recursive directories for outputs.

**Breaking changes**

## Related Issue / Discussion

- Should allow custom nested directories to be configured for outputs (see #11 &  #203)

- Corresponding notebook changes: https://github.com/Ouranosinc/pavics-sdi/pull/244

### CODE REVIEW

**Comment by tlvu** [comment]
@tlogan2000 You've asked to keep PAVICS unchanged before your demo in a week.  Are you only using xclim in the Jupyter env or you'll also use Finch.  If yes, do you want to audit this Finch upgrade?

**Review by tlvu — APPROVED** [review]
climex, forecasts and subset-user-input notebook failure fixed in PR https://github.com/Ouranosinc/pavics-sdi/pull/244.  The weaver one is a known failure.

PR good to go.  Don't forget the usual release note update, bump version process and tagging after merge.

I'd also wait for an OK from Travis.  He has requested for the env not to change for his upcoming demo.

**Comment by tlvu** [comment]
run tests

**Comment by tlvu** [comment]
Talked to @aulemahal this morning.  He's thinking about releasing a newer Finch so maybe we don't merge this PR but wait for his newer Finch.

Do we have a need for this Finch right now or it can wait.

**Comment by huard** [comment]
My main concern is allowing progress on the related issues outlined in the description. If you're not going to work on them before Pascal's next release, then the delay doesn't matter.

**Comment by tlvu** [comment]
> My main concern is allowing progress on the related issues outlined in the description. If you're not going to work on them before Pascal's next release, then the delay doesn't matter.

Yes I have a few other things on my plate but I do not need a real go-live to be able to test the other related issues.

**Comment by tlvu** [comment]
I tested this new Finch with new wps config to create the different dirs:

https://github.com/bird-house/birdhouse-deploy/blob/a4ba10e542bdbbad6937a763fe885447df40970f/birdhouse/config/finch/wps.cfg.template#L2-L8

Unfortunately I am getting the following errors:
```
$ docker logs finch                                                                                                           
[2022-02-03 15:37:30 +0000] [1] [INFO] Starting gunicorn 20.1.0                                                                                       
[2022-02-03 15:37:30 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)                                                                          
[2022-02-03 15:37:30 +0000] [1] [INFO] Using worker: sync                                                                                             
[2022-02-03 15:37:30 +0000] [6] [INFO] Booting worker with pid: 6                                                                                     
server->workdir configuration value /data/wpsoutputs/finch/workdir is not directory                                                                   
server->outputpath configuration value /data/wpsoutputs/finch is not directory                                                                        
[2022-02-03 15:38:00 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:6)                                                                                     
[2022-02-03 15:38:00 +0000] [6] [INFO] Worker exiting (pid: 6)                                                                                        
[2022-02-03 15:38:01 +0000] [1] [WARNING] Worker with pid 6 was terminated due to signal 9 
```

Will diagnose and report further findings.

**Comment by tlvu** [comment]
Tried a notebook on Finch just in case the error about dir not created are false positive, confirmed the error about dir creation is real.
```
2022-02-03 16:18:29,720 - PYWPS - ERROR - Exception: code: 500, description: No applicable error code, please check error log., locator:
Traceback (most recent call last):
  File "/opt/conda/envs/finch/lib/python3.9/site-packages/pywps/app/Service.py", line 314, in call
    raise e
  File "/opt/conda/envs/finch/lib/python3.9/site-packages/pywps/app/Service.py", line 304, in call
    response = self.execute(
  File "/opt/conda/envs/finch/lib/python3.9/site-packages/pywps/app/Service.py", line 81, in execute
    process = self.prepare_process_for_execution(identifier)
  File "/opt/conda/envs/finch/lib/python3.9/site-packages/pywps/app/Service.py", line 97, in prepare_process_for_execution
    tempdir = tempfile.mkdtemp(prefix='pywps_process_', dir=workdir)
  File "/opt/conda/envs/finch/lib/python3.9/tempfile.py", line 363, in mkdtemp
    _os.mkdir(file, 0o700)
FileNotFoundError: [Errno 2] No such file or directory: '/data/wpsoutputs/finch/workdir/pywps_process_8z895epm'
```

**Comment by Zeitsperre** [comment]
Closing. Superseded by #235

**Pull request closed without merging**
