### PR TITLE
Add a zenodo configuration

### PR DESCRIPTION
**Pull request by Zeitsperre**
## Overview

Please include a summary of the changes and which issues are fixed. 

Please also include relevant motivation and context. 

List any dependencies that are required for this change.

## Changes

**Non-breaking changes**
- Adds a Zenodo configuration 

## Related Issue / Discussion

- Resolves [#299](https://github.com/bird-house/birdhouse-deploy/issues/299) 

## Additional Information

 - ~Zenodo has not yet been enabled on the repository.~ Enabled
 - This project also does not contain a License file, so I have not added any license or access rights to the configuration.

### CODE REVIEW

**Review by huard — APPROVED** [review]

**Comment by huard** [comment]
@mishaschwartz You'll probably want to add your name here.

**Comment by huard** [comment]
@tlvu Once this is merged, would it be possible to make a release to trigger the hook ?

**Comment by tlvu** [comment]
> @tlvu Once this is merged, would it be possible to make a release to trigger the hook ? Doesn't have to be now, just over the next 2-3 weeks.

What is the definition of a release?  A tag we usually do?  Or I have to run a specific command to trigger zenodo release?

**Review by tlvu — APPROVED** [review]
LGTM.  Can you add something to the changlog (CHANGES.md at the root of the repo)?

I'll merge once everyone approve, to double check their orcid I guess?

**Review by fmigneault — APPROVED** [review]

**Comment by huard** [comment]
A release is different from a tag. A release creates artifacts (source code snapshot) that are preserved as a zip of the repo. This is then pushed to zenodo for long-term archival. https://github.com/bird-house/birdhouse-deploy/releases

**Comment by fmigneault** [comment]
To play devil's advocate, all tags also got their ZIP: 
https://github.com/bird-house/birdhouse-deploy/archive/refs/tags/1.23.3.zip

**Comment by fmigneault** [comment]
@tlvu 
An action like https://github.com/marketplace/actions/auto-release could be used to make all releases available automatically on bump/tags pushed. It could include details by injecting the part of `CHANGES.md` applicable for the release.

**Comment by huard** [comment]
My bad, so not clear exactly what the distinction is, but I believe the default zenodo setting is to archive on releases. Again  I could be wrong...

**Comment by huard** [comment]
The zenodo webhook could be triggered by "Branch or tag created.", but I'm concern this would create lots of noise. 
I suggest that once in a while, we designate a "major" change as a release.

**Comment by fmigneault** [comment]
> My bad, so not clear exactly what the distinction is, but I believe the default zenodo setting is to archive on releases.

That would probably be the case because releases offer a way to include the changelog explicitly, while the tag doesn't *directly* provide it. 

> The zenodo webhook could be triggered by "Branch or tag created.", but I'm concern this would create lots of noise.
I suggest that once in a while, we designate a "major" change as a release.

I agree that it would be too noisy for each tag, but I think it would be relevant to include "minor" at least since those include important changes, like new features/components. Major are used only in "hard" breaking changes, and we have so far only 1. 

There is usually a good amount of "patch" versions between each "minor" to make each minor-level tag a considerable release.

**Comment by tlvu** [comment]
> The zenodo webhook could be triggered by "Branch or tag created.", but I'm concern this would create lots of noise. I suggest that once in a while, we designate a "major" change as a release.

@huard 
You're afraid too much noise on Zenodo side if we let it trigger on "branch or tag created"? I would not use branch but tag only.  We do not tag/release that frequently, probably once every 2-4 weeks.  Is that too much?  On the flip side, it shows on Zenodo the project is active.

Otherwise yes a manual release (once a year?) from time to time is fine for me.  

I could simply create a release from an existing tag right now to finalize the process with Zenodo.  We can discuss later if we want auto publish to Zenodo on each tag or manual creating a release from time to time.

**Comment by Zeitsperre** [comment]
@tlvu

There's an action available specifically for publishing to Zenodo (https://github.com/kykrueger/zenodo-publish). If we wanted to trigger this manually or via a specific event (tag, release, cron job, etc.), we could also take this approach as well.

**Comment by tlvu** [comment]
> @tlvu
> 
> There's an action available specifically for publishing to Zenodo (https://github.com/kykrueger/zenodo-publish). If we wanted to trigger this manually or via a specific event (tag, release, cron job, etc.), we could also take this approach as well.

@Zeitsperre 

Did you have to enable this action for all the other repos you've been adding Zenodo to recently?

What is your "publish to Zenodo" frequency in all the other repos?  On each tag?  On manual release creation?

I'll try to follow your existing procedure if I can.  Let me know.

**Comment by Zeitsperre** [comment]
> Did you have to enable this action for all the other repos you've been adding Zenodo to recently?

Yes, this can be done by connecting to zenodo.org and syncing your repositories with GitHub. Those you have rights to will have an "on/off" switch. Once enabled, Zenodo will accept payloads from GitHub

> What is your "publish to Zenodo" frequency in all the other repos? On each tag? On manual release creation?

In our setup on xclim (and all others synced via Zenodo/GitHub integration), the payload is triggered on `"action": "published"`. The `zenodo-publish` action exists in order to create a new published version with Zenodo under different events/actions (e.g. on tag creation, on push to master, via workflow-dispatch, etc.)

Publishing versions on GitHub seems like the best way forward. There are methods for automatically creating published versions on tagged commits, so perhaps that might be an option here?

**Comment by huard** [comment]
@mishaschwartz Do you want to add your name here? I'd like to get this merged ASAP for a paper.

**Comment by tlvu** [comment]
@Zeitsperre Looks like @huard wants to merge this fast for a paper. I just want recap how to publish to Zenodo:
* merge this PR
* manually create a release from an existing tag at https://github.com/bird-house/birdhouse-deploy/releases/new?tag=1.25.0
* Zenodo will auto-magically see this release and publish on Zenodo side?

If there are additional setup on Zenodo side, could you do it since you have done quite a few of those.

**Comment by Zeitsperre** [comment]
@tlvu 

That is the exact procedure to follow. Everything is set up for Zenodo publishing. Go for it!

**Comment by huard** [comment]
Can this be merged ?

**Comment by tlvu** [comment]
A release was created here https://github.com/bird-house/birdhouse-deploy/releases/tag/1.26.1, hopefully a Zenodo release is created successfully.

**Comment by fmigneault** [comment]
It worked: https://zenodo.org/record/7865538
I got pinged by zenodo to accept the record in my list of associated publications.

**Pull request merged**
