### PR TITLE
Fix disapearing Thredds docker image 4.6.18

### PR DESCRIPTION
**Pull request by mishaschwartz**
## Overview

  The current docker image version for thredds (4.6.18) is no longer hosted in the [Unidata docker repository](https://hub.docker.com/r/unidata/thredds-docker/tags).

  Pushed the same image from Ouranos production to PAVICS DockerHub, restoring
  the missing Thredds image.

  Discovered that Unidata is also not keeping their tag immutable, like Kartoza Geoserver image.

  So Ouranos tag has the approximate month of Unidata re-release of 4.6.18.

  On our production server:
  ```
  $ docker images |grep thredds|grep 4.6.18
  unidata/thredds-docker              4.6.18              25997a1b2893   15 months ago   5.63GB
  ```

  On our staging server:
  ```
  $ docker images |grep thredds | grep 4.6.18
  unidata/thredds-docker              4.6.18              09103737360a   16 months ago   5.62GB
  ```

## Changes

**Non-breaking changes**

- Restore the same Thredds docker image as the one on Ouranos production

### CODE REVIEW

**Comment by mishaschwartz** [comment]
@matprov 

The current docker version running on jenkins does not support the updated tomcat image used by this version of thredds.

Current version is 18.09.2 (see image below) and I believe this breaks prior to version 20 (https://github.com/docker-library/tomcat/issues/269).

Screenshot from 2023-04-11 13-12-58

Can we update the Jenkins build? If this is something that I can do can you please remind me where to do so?

**Comment by tlvu** [comment]
@mishaschwartz Quick fix, since we do not have access to the Jenkins host, is to push the current thredds 4.6.18 to pavics dockerhub, so we basically "restore" the same binary.

Safer too since I do not have to test upgrade Thredds.  We have quite a large quantity of .nc and .ncml files so I'd rather not take a chance.

Will push to this branch, unless you prefer me to PR on top of this PR?

**Comment by mishaschwartz** [comment]
@tlvu please feel free to push to this branch. Thanks!

**Comment by tlvu** [comment]
@mishaschwartz Wait for a working Jenkins before merging this.

Given I discovered Thredds image tag are not immutable, I think we should also cache the next upgrade to pavics DockerHub to ensure reproductibility.

**Comment by mishaschwartz** [comment]
@tlvu 

> Given I discovered Thredds image tag are not immutable, I think we should also cache the next upgrade to pavics DockerHub to ensure reproductibility.

Oh good catch! Ok I'll wait for the tests and then I'll merge

**Comment by mishaschwartz** [comment]
run tests

**Comment by tlvu** [comment]
This is very weird, let me do a manual check.  Maybe fat finger I tagged the wrong image ...

**Comment by tlvu** [comment]
The PR starts fine on my test VM.  I think you can merge this.

**Comment by tlvu** [comment]
> # E2E Test Results
> ## DACCS-iac Pipeline Results
> Build URL : http://daccs-jenkins.crim.ca:80/job/DACCS-iac-birdhouse/1439/
> Result : failure
> 
> BIRDHOUSE_DEPLOY_BRANCH : update-thredds
> DACCS_CONFIGS_BRANCH : master
> PAVICS_E2E_WORKFLOW_TESTS_BRANCH : master
> PAVICS_SDI_BRANCH : master
> 
> DESTROY_INFRA_ON_EXIT : true
> PAVICS_HOST : https://host-140-216.rdext.crim.ca
> 
> Infrastructure deployment failed. Instance has not been destroyed. @matprov

@matprov FYI, it seems the instance did not start.

[CHECK] Waiting for canarie-api [https://host-140-216.rdext.crim.ca/canarie/node/service/status]...
....................................................................................................................................................................................................................................
[WARNING] Timeout of [1200] seconds reached. Exiting, but leaving the instance running.

```
$ curl  --include https://host-140-216.rdext.crim.ca/
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to host-140-216.rdext.crim.ca:443 

$ curl  --include http://host-140-216.rdext.crim.ca/
curl: (56) Recv failure: Connection reset by peer

# just to have the IP
$ ping host-140-216.rdext.crim.ca
PING host-140-216.rdext.crim.ca (132.217.140.216) 56(84) bytes of data.
# ping no response as well
```

**Comment by fmigneault** [comment]
Can [4.6.20](https://hub.docker.com/layers/unidata/thredds-docker/4.6.20/images/sha256-d5ba9db24400eb007e8cdf259a694637ccb4bef6585ef188707931d4f77c345d?context=explore) be used instead?
Still a good idea to cache them on our side though to avoid disappearing tags.

**Comment by tlvu** [comment]
> Can [4.6.20](https://hub.docker.com/layers/unidata/thredds-docker/4.6.20/images/sha256-d5ba9db24400eb007e8cdf259a694637ccb4bef6585ef188707931d4f77c345d?context=explore) be used instead? 

I think no, see https://github.com/bird-house/birdhouse-deploy/pull/313#issuecomment-1503802979

**Comment by tlvu** [comment]
> I think the docker engine is predefined and static on the E2E instance. I think updating it would require more manual steps to make sure any relevant plugins will still work with it.

@fmigneault 
You're right!  Let's not feature creep this PR with upgrading the docker engine which might need Jenkins and all its plugins upgraded as well (upgrade for the docker plugin as least).

As for Thredds 4.6.20, from what @mishaschwartz found out, it might need a new docker engine. I find this pretty weird but I don't have time to investigate.

This disappering Thredds image tag is breaking all the pipeline now so I think we should put off the fire first and schedule an upgrade later when @matprov is back.

**Comment by mishaschwartz** [comment]
@tlvu just confirming based on the discussion above that the current docker image the one we want to stick with for now? (pavics/thredds-docker:4.6.18-unidata-2022-01)

If so I can merge this in.

**Comment by tlvu** [comment]
> @tlvu just confirming based on the discussion above that the current docker image the one we want to stick with for now? (pavics/thredds-docker:4.6.18-unidata-2022-01)
> 
> If so I can merge this in.

Exact, merge party for you today :D

**Pull request merged**
