### PR TITLE
GeoServer: enable metadata-plugin for modifying layer metadata, including bulk modifications

### PR DESCRIPTION
**Pull request by tlvu**
See plugin documentation at https://docs.geoserver.org/2.19.x/en/user/community/metadata/index.html

Related to issue https://github.com/Ouranosinc/pavics-sdi/issues/234

Add new "Metadata" tab in Layer Edit page:
Screenshot 2022-01-25 at 00-25-45 GeoServer Edit Layer

### CODE REVIEW

**Review by huard — APPROVED** [review]
Ok for me but I'll leave the final word to @Zeitsperre.

**Comment by tlvu** [comment]
> Ok for me but I'll leave the final word to @Zeitsperre.

Yes of course.  This is so that I do not have valuable code layout around on my machine and risking to lose it if my disk is corrupted.

I understand we are still in exploratory phase and maybe this plugin do not even do what we need.  @Zeitsperre can take as much time as he needs to test this.

**Comment by Zeitsperre** [comment]
@tlvu Thanks for this. I'll give it a look and see. I think when it comes to streaming metadata, this is likely our only option until the industry advances in adopting the existing metadata standards for geospatial data generally. The goal is to give this all a look this week!

**Comment by tlvu** [comment]
@Zeitsperre have you had the time to work on this?  Do you still need my test server?  See https://github.com/Ouranosinc/pavics-sdi/issues/234#issuecomment-1021330230

**Comment by Zeitsperre** [comment]
> @Zeitsperre have you had the time to work on this? Do you still need my test server? See [Ouranosinc/pavics-sdi#234 (comment)](https://github.com/Ouranosinc/pavics-sdi/issues/234#issuecomment-1021330230)

@tlvu Yes, it would be convenient if you could keep that running. I'll aim to try it out this afternoon if possible!

**Comment by tlvu** [comment]
> > @Zeitsperre have you had the time to work on this? Do you still need my test server? See [Ouranosinc/pavics-sdi#234 (comment)](https://github.com/Ouranosinc/pavics-sdi/issues/234#issuecomment-1021330230)
> 
> @tlvu Yes, it would be convenient if you could keep that running. I'll aim to try it out this afternoon if possible!

@Zeitsperre Any update?

**Comment by Zeitsperre** [comment]
@aulemahal @cjauvin 

I know that you two have been working on effective use of GeoServer metadata in the past few months. Do either of you see any benefits from this plugin?

**Comment by cjauvin** [comment]
It seems interesting but in our context (Portraits climatiques) the metadata have been kept at the NC file level. Maybe there would be a case for transfering them at the GS layer level, if we ever want to expose the WMS service in a more official way?

**Pull request merged**
